### ISSUE TITLE
Kafka Advertised Listeners

### ISSUE THREAD

**Issue by archmangler** [archmangler/kubernetes-networking-cookbook#2]
I have kafka installed from helm chart on kubernetes on Azure.

- The following is the advertised listeners configuration in the kafka statefulset:

```
export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_NAME}.lol-kafka-cp-kafka-headless.${POD_NAMESPACE}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
```

- How can I modify this kafka statefulset yaml configuration to include a public address like the following as one of the kafka advertised listeners:

```
kafka.lol.com:9092
```

**Comment by archmangler** [comment]
```
env:
  - name: KAFKA_ADVERTISED_LISTENERS
    value: "PLAINTEXT://${POD_NAME}.lol-kafka-cp-kafka-headless.${POD_NAMESPACE}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})),PUBLIC://kafka.lol.com:9092"
  - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
    value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,PUBLIC:PLAINTEXT"
  - name: KAFKA_LISTENERS
    value: "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:31090,PUBLIC://0.0.0.0:9092"

```
