### ISSUE TITLE
Convert a working ingress to using TLS for a single service

### ISSUE THREAD

**Issue by archmangler** [archmangler/kubernetes-networking-cookbook#3]
I have the following working ingress configuration (non-TLS):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lol-ingress
  namespace: lol  # The namespace where the Ingress will reside
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "lol.lol.com"  # Replace with the public IP address of the Ingress Controller
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: litigate
            port:
              number: 5606
```

I would like to modify this ingress to provide TLS from the user (on the internet) to the ingress entry point (nginx ingress controller running on Azure AKS).

What are the steps I should take to;

a) modify the ingress configuration
b) Generate a free TLS certificate

**Comment by archmangler** [comment]
Step A: Modify the Ingress Configuration for TLS

- Update your Ingress configuration to include TLS settings:

(Updated Ingress YAML with TLS)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lol-ingress
  namespace: lol  # The namespace where the Ingress will reside
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Reference to Cert-Manager (Step B)
spec:
  tls:
    - hosts:
        - lol.lol.com  # Your domain
      secretName: lol-tls-secret  # TLS Secret that stores the certificate
  rules:
    - host: "lol.lol.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litigate
                port:
                  number: 5606
```

📌 Explanation of Changes:

- Added tls: section to specify the domain and the secret storing the TLS certificate.
- Added the annotation cert-manager.io/cluster-issuer, which will allow Let's Encrypt (Step B) to automatically generate a free SSL certificate.

🔹 Step B: Generate a Free TLS Certificate using Let’s Encrypt

To issue a Let's Encrypt TLS certificate, follow these steps:

1️⃣ Install Cert-Manager on Your AKS Cluster

- Cert-Manager automates certificate management for Kubernetes.

```bash
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
```

- Verify that Cert-Manager is installed:

```bash
kubectl get pods -n cert-manager
```

2️⃣ Create a Cluster Issuer for Let's Encrypt


- Create a YAML file named cluster-issuer.yaml:

```yaml
Copy
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
```

- Apply the ClusterIssuer:

```bash
kubectl apply -f cluster-issuer.yaml
```

- Verify the ClusterIssuer is ready:

```bash
kubectl get clusterissuer
```

3️⃣ Apply the Updated Ingress

- Apply your updated Ingress configuration (from Step A):

```bash
kubectl apply -f lol-ingress.yaml
```

- Cert-Manager will now automatically request a free Let's Encrypt certificate, store it in the secret lol-tls-secret, and enable HTTPS.

🔹 Step C: Verify TLS

Check if the certificate is issued successfully:

```bash
kubectl describe certificate -n lol
```

Access your service using HTTPS: https://lol.lol.com


If needed, check logs:

```
kubectl logs -n cert-manager -l app=cert-manager
```

🎉 Done!

🚀 Your Ingress now supports TLS encryption using a free Let’s Encrypt certificate in Azure AKS. 

Let me know if you need any further troubleshooting help! 🔒✨

**Comment by archmangler** [comment]
Ingress address keeps toggling between private IP address and the public IP address:

```
I0211 06:36:57.490700       7 event.go:377] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"siren", Name:"siren-ingress", UID:"543d2f97-8143-4aaa-a26b-70a891f815cc", APIVersion:"networking.k8s.io/v1", ResourceVersion:"44079598", FieldPath:""}): 
type: 'Normal' reason: 'Sync' Scheduled for sync
I0211 06:37:54.549838       7 status.go:304] "updating Ingress status" namespace="siren" ingress="siren-ingress" currentValue=[{"ip":"10.0.1.183"}] newValue=[{"ip":"172.188.205.71"}]
I0211 06:37:54.763129       7 event.go:377] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"siren", Name:"siren-ingress", UID:"543d2f97-8143-4aaa-a26b-70a891f815cc", APIVersion:"networking.k8s.io/v1", ResourceVersion:"44080087", FieldPath:""}): 
type: 'Normal' reason: 'Sync' Scheduled for sync
```

My ingress configuration:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: flute-ingress
  namespace: flute  # The namespace where the Ingress will reside
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Reference to Cert-Manager (Step B)
spec:
  tls:
    - hosts:
- flute.acn-lol.com  # Your domain
secretName: flute-tls-secret  # TLS Secret that stores the certificate
  rules:
    - host: "flute.acn-lol.com"
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: investigate
port:
number: 5606
```

**Comment by archmangler** [comment]
This is my ingress controller:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: kafka-ingress
  namespace: kafka-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "TLS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
- kafka.acn-aisles.com
    secretName: kafka-ingress-tls
  rules:
  - host: kafka.acn-aisles.com
    http:
paths:
- path: /
pathType: ImplementationSpecific
backend:
service:
name: kafka-ingress-controller
port:
number: 9093
- path: /
pathType: Prefix
backend:
service:
name: kafka-ingress-controller
port:
number: 9092  # Non-TLS Kafka port
```

**Comment by archmangler** [comment]
check the ingressclass:

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx-secondary  # Must match the ingressClassName in siren-ingress
spec:
  controller: k8s.io/ingress-nginx
```
